
import java.awt.Color;
import java.awt.Label;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FABRIK
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        TEAM1TXT.setText("");
        TEAM2TXT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        StartPanel = new javax.swing.JPanel();
        PLAY = new javax.swing.JButton();
        HISTORY = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        choosePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        blue1 = new javax.swing.JButton();
        red1 = new javax.swing.JButton();
        red2 = new javax.swing.JButton();
        green2 = new javax.swing.JButton();
        blue2 = new javax.swing.JButton();
        yellow2 = new javax.swing.JButton();
        green1 = new javax.swing.JButton();
        yellow1 = new javax.swing.JButton();
        chooseback = new javax.swing.JButton();
        chooseplay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chooseTeam1Label = new javax.swing.JLabel();
        chooseTeam2Label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        playPanel = new javax.swing.JPanel();
        TEAM1TITPLUS = new javax.swing.JButton();
        TEAM1TITMIN = new javax.swing.JButton();
        TEAM1GRAPLUS = new javax.swing.JButton();
        TEAM1GRAMIN = new javax.swing.JButton();
        TEAM2TITPLUS = new javax.swing.JButton();
        TEAM2TITMIN = new javax.swing.JButton();
        TEAM2GRAPLUS = new javax.swing.JButton();
        TEAM2GRAMIN = new javax.swing.JButton();
        commit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        playTeam1Label = new javax.swing.JLabel();
        playTeam2Label = new javax.swing.JLabel();
        TEAM1SCORE = new javax.swing.JLabel();
        TEAM2SCORE = new javax.swing.JLabel();
        TEAM1TXT = new javax.swing.JTextField();
        TEAM2TXT = new javax.swing.JTextField();
        endGame = new javax.swing.JButton();
        UNDO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        historyLabel = new javax.swing.JLabel();
        backHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        team1scoreHistory = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        team2scoreHistory = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(365, 679, 679, 679));
        setMaximumSize(new java.awt.Dimension(365, 679));
        setPreferredSize(new java.awt.Dimension(365, 679));
        setResizable(false);

        StartPanel.setMaximumSize(new java.awt.Dimension(365, 679));
        StartPanel.setMinimumSize(new java.awt.Dimension(365, 679));
        StartPanel.setPreferredSize(new java.awt.Dimension(365, 679));
        StartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PLAY.setBackground(new java.awt.Color(0, 153, 0));
        PLAY.setFont(new java.awt.Font("Showcard Gothic", 1, 22)); // NOI18N
        PLAY.setForeground(new java.awt.Color(255, 255, 255));
        PLAY.setText("PLAY");
        PLAY.setMaximumSize(new java.awt.Dimension(180, 40));
        PLAY.setMinimumSize(new java.awt.Dimension(180, 40));
        PLAY.setPreferredSize(new java.awt.Dimension(180, 40));
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        StartPanel.add(PLAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        HISTORY.setBackground(new java.awt.Color(0, 153, 204));
        HISTORY.setFont(new java.awt.Font("Showcard Gothic", 1, 22)); // NOI18N
        HISTORY.setForeground(new java.awt.Color(255, 255, 255));
        HISTORY.setText("HISTORY");
        HISTORY.setMaximumSize(new java.awt.Dimension(180, 40));
        HISTORY.setMinimumSize(new java.awt.Dimension(180, 40));
        HISTORY.setPreferredSize(new java.awt.Dimension(180, 40));
        HISTORY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HISTORYActionPerformed(evt);
            }
        });
        StartPanel.add(HISTORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        EXIT.setBackground(new java.awt.Color(204, 0, 0));
        EXIT.setFont(new java.awt.Font("Showcard Gothic", 1, 22)); // NOI18N
        EXIT.setForeground(new java.awt.Color(255, 255, 255));
        EXIT.setText("EXIT");
        EXIT.setMaximumSize(new java.awt.Dimension(180, 40));
        EXIT.setMinimumSize(new java.awt.Dimension(180, 40));
        EXIT.setPreferredSize(new java.awt.Dimension(180, 40));
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        StartPanel.add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dragon1.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(367, 679));
        StartPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        choosePanel.setBackground(new java.awt.Color(255, 255, 255));
        choosePanel.setMaximumSize(new java.awt.Dimension(365, 679));
        choosePanel.setMinimumSize(new java.awt.Dimension(365, 679));
        choosePanel.setPreferredSize(new java.awt.Dimension(365, 679));
        choosePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHOOSE COLORS");
        choosePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 90));

        blue1.setBackground(new java.awt.Color(0, 0, 204));
        blue1.setMaximumSize(new java.awt.Dimension(40, 40));
        blue1.setMinimumSize(new java.awt.Dimension(40, 40));
        blue1.setPreferredSize(new java.awt.Dimension(40, 40));
        blue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blue1ActionPerformed(evt);
            }
        });
        choosePanel.add(blue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        red1.setBackground(new java.awt.Color(255, 0, 0));
        red1.setMaximumSize(new java.awt.Dimension(40, 40));
        red1.setMinimumSize(new java.awt.Dimension(40, 40));
        red1.setPreferredSize(new java.awt.Dimension(40, 40));
        red1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                red1ActionPerformed(evt);
            }
        });
        choosePanel.add(red1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        red2.setBackground(new java.awt.Color(255, 0, 0));
        red2.setMaximumSize(new java.awt.Dimension(40, 40));
        red2.setMinimumSize(new java.awt.Dimension(40, 40));
        red2.setPreferredSize(new java.awt.Dimension(40, 40));
        red2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                red2ActionPerformed(evt);
            }
        });
        choosePanel.add(red2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        green2.setBackground(new java.awt.Color(0, 204, 51));
        green2.setMaximumSize(new java.awt.Dimension(40, 40));
        green2.setMinimumSize(new java.awt.Dimension(40, 40));
        green2.setPreferredSize(new java.awt.Dimension(40, 40));
        green2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                green2ActionPerformed(evt);
            }
        });
        choosePanel.add(green2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        blue2.setBackground(new java.awt.Color(0, 0, 204));
        blue2.setMaximumSize(new java.awt.Dimension(40, 40));
        blue2.setMinimumSize(new java.awt.Dimension(40, 40));
        blue2.setPreferredSize(new java.awt.Dimension(40, 40));
        blue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blue2ActionPerformed(evt);
            }
        });
        choosePanel.add(blue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        yellow2.setBackground(new java.awt.Color(255, 255, 0));
        yellow2.setMaximumSize(new java.awt.Dimension(40, 40));
        yellow2.setMinimumSize(new java.awt.Dimension(40, 40));
        yellow2.setPreferredSize(new java.awt.Dimension(40, 40));
        yellow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellow2ActionPerformed(evt);
            }
        });
        choosePanel.add(yellow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        green1.setBackground(new java.awt.Color(0, 204, 51));
        green1.setMaximumSize(new java.awt.Dimension(40, 40));
        green1.setMinimumSize(new java.awt.Dimension(40, 40));
        green1.setPreferredSize(new java.awt.Dimension(40, 40));
        green1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                green1ActionPerformed(evt);
            }
        });
        choosePanel.add(green1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        yellow1.setBackground(new java.awt.Color(255, 255, 0));
        yellow1.setMaximumSize(new java.awt.Dimension(40, 40));
        yellow1.setMinimumSize(new java.awt.Dimension(40, 40));
        yellow1.setPreferredSize(new java.awt.Dimension(40, 40));
        yellow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellow1ActionPerformed(evt);
            }
        });
        choosePanel.add(yellow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        chooseback.setBackground(new java.awt.Color(204, 0, 0));
        chooseback.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        chooseback.setForeground(new java.awt.Color(255, 255, 255));
        chooseback.setText("BACK");
        chooseback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosebackActionPerformed(evt);
            }
        });
        choosePanel.add(chooseback, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 120, 40));

        chooseplay.setBackground(new java.awt.Color(0, 153, 0));
        chooseplay.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        chooseplay.setForeground(new java.awt.Color(255, 255, 255));
        chooseplay.setText("PLAY");
        chooseplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseplayActionPerformed(evt);
            }
        });
        choosePanel.add(chooseplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 120, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 340));
        choosePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 300));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 340));
        choosePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, 300));

        chooseTeam1Label.setBackground(new java.awt.Color(0, 0, 0));
        chooseTeam1Label.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        chooseTeam1Label.setForeground(new java.awt.Color(255, 255, 255));
        chooseTeam1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseTeam1Label.setText("TEAM 1");
        chooseTeam1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        choosePanel.add(chooseTeam1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, 40));

        chooseTeam2Label.setBackground(new java.awt.Color(0, 0, 0));
        chooseTeam2Label.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        chooseTeam2Label.setForeground(new java.awt.Color(255, 255, 255));
        chooseTeam2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseTeam2Label.setText("TEAM 2");
        chooseTeam2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        chooseTeam2Label.setPreferredSize(new java.awt.Dimension(84, 35));
        choosePanel.add(chooseTeam2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundDragon.png"))); // NOI18N
        choosePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        playPanel.setMaximumSize(new java.awt.Dimension(365, 679));
        playPanel.setMinimumSize(new java.awt.Dimension(365, 679));
        playPanel.setPreferredSize(new java.awt.Dimension(365, 679));
        playPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TEAM1TITPLUS.setBackground(new java.awt.Color(0, 204, 51));
        TEAM1TITPLUS.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM1TITPLUS.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM1TITPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM1TITPLUSActionPerformed(evt);
            }
        });
        playPanel.add(TEAM1TITPLUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 50));

        TEAM1TITMIN.setBackground(new java.awt.Color(255, 0, 0));
        TEAM1TITMIN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM1TITMIN.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM1TITMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM1TITMINActionPerformed(evt);
            }
        });
        playPanel.add(TEAM1TITMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 50));

        TEAM1GRAPLUS.setBackground(new java.awt.Color(0, 204, 51));
        TEAM1GRAPLUS.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM1GRAPLUS.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM1GRAPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM1GRAPLUSActionPerformed(evt);
            }
        });
        playPanel.add(TEAM1GRAPLUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, 50));

        TEAM1GRAMIN.setBackground(new java.awt.Color(255, 0, 0));
        TEAM1GRAMIN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM1GRAMIN.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM1GRAMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM1GRAMINActionPerformed(evt);
            }
        });
        playPanel.add(TEAM1GRAMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 50));

        TEAM2TITPLUS.setBackground(new java.awt.Color(0, 204, 51));
        TEAM2TITPLUS.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM2TITPLUS.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM2TITPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM2TITPLUSActionPerformed(evt);
            }
        });
        playPanel.add(TEAM2TITPLUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 50));

        TEAM2TITMIN.setBackground(new java.awt.Color(255, 0, 0));
        TEAM2TITMIN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM2TITMIN.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM2TITMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM2TITMINActionPerformed(evt);
            }
        });
        playPanel.add(TEAM2TITMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, 50));

        TEAM2GRAPLUS.setBackground(new java.awt.Color(0, 204, 51));
        TEAM2GRAPLUS.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM2GRAPLUS.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM2GRAPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM2GRAPLUSActionPerformed(evt);
            }
        });
        playPanel.add(TEAM2GRAPLUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, 50));

        TEAM2GRAMIN.setBackground(new java.awt.Color(255, 0, 0));
        TEAM2GRAMIN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TEAM2GRAMIN.setPreferredSize(new java.awt.Dimension(90, 40));
        TEAM2GRAMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEAM2GRAMINActionPerformed(evt);
            }
        });
        playPanel.add(TEAM2GRAMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, 50));

        commit.setBackground(new java.awt.Color(255, 255, 0));
        commit.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        commit.setForeground(new java.awt.Color(255, 255, 255));
        commit.setText("commit");
        commit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        commit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitActionPerformed(evt);
            }
        });
        playPanel.add(commit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("tichu +");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 30));
        playPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 120, 50));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("tichu -");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 30));
        playPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 120, 50));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("grand +");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 30));
        playPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 120, 50));

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("grand -");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 30));
        playPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 120, 50));

        playTeam1Label.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N
        playTeam1Label.setForeground(new java.awt.Color(255, 255, 255));
        playTeam1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playTeam1Label.setText("team");
        playTeam1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playTeam1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playPanel.add(playTeam1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 40));

        playTeam2Label.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N
        playTeam2Label.setForeground(new java.awt.Color(255, 255, 255));
        playTeam2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playTeam2Label.setText("team");
        playTeam2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playTeam2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playPanel.add(playTeam2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, 40));

        TEAM1SCORE.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TEAM1SCORE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEAM1SCORE.setText("0");
        TEAM1SCORE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playPanel.add(TEAM1SCORE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 50));

        TEAM2SCORE.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TEAM2SCORE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TEAM2SCORE.setText("0");
        TEAM2SCORE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playPanel.add(TEAM2SCORE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, 50));

        TEAM1TXT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TEAM1TXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        playPanel.add(TEAM1TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 60));

        TEAM2TXT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TEAM2TXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        playPanel.add(TEAM2TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, 60));

        endGame.setBackground(new java.awt.Color(0, 153, 204));
        endGame.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        endGame.setForeground(new java.awt.Color(255, 255, 255));
        endGame.setText("END GAME");
        endGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endGameActionPerformed(evt);
            }
        });
        playPanel.add(endGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 581, 160, 40));

        UNDO.setBackground(new java.awt.Color(102, 102, 102));
        UNDO.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        UNDO.setForeground(new java.awt.Color(255, 255, 255));
        UNDO.setText("UNDO");
        UNDO.setOpaque(false);
        UNDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNDOActionPerformed(evt);
            }
        });
        playPanel.add(UNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        playPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 300, 200));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TICHU COUNTER");
        playPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 300, 80));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 280, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundDragon.png"))); // NOI18N
        playPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        historyPanel.setMaximumSize(new java.awt.Dimension(365, 679));
        historyPanel.setMinimumSize(new java.awt.Dimension(365, 679));
        historyPanel.setPreferredSize(new java.awt.Dimension(365, 679));
        historyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        historyLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 40)); // NOI18N
        historyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyLabel.setText("HISTORY");
        historyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        historyPanel.add(historyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 365, 90));

        backHistory.setBackground(new java.awt.Color(204, 0, 0));
        backHistory.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        backHistory.setForeground(new java.awt.Color(255, 255, 255));
        backHistory.setText("BACK");
        backHistory.setPreferredSize(new java.awt.Dimension(120, 40));
        backHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHistoryActionPerformed(evt);
            }
        });
        historyPanel.add(backHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        team1scoreHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team1scoreHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        team1scoreHistory.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        team1scoreHistory.setEnabled(false);
        jScrollPane1.setViewportView(team1scoreHistory);

        historyPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 183, 450));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        team2scoreHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        team2scoreHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        team2scoreHistory.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        team2scoreHistory.setEnabled(false);
        jScrollPane2.setViewportView(team2scoreHistory);

        historyPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 184, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundDragon.png"))); // NOI18N
        historyPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(StartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(historyPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StartPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choosePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
        StartPanel.setVisible(false);
        choosePanel.setVisible(true);
        chooseTeam1Label.setBackground(Color.blue);
        chooseTeam1Label.setOpaque(true);
        blue2.setEnabled(false);
        red2.setEnabled(true);
        yellow2.setEnabled(true);
        green2.setEnabled(true);
        chooseTeam2Label.setBackground(Color.red);
         chooseTeam2Label.setOpaque(true);
        blue1.setEnabled(true);
        red1.setEnabled(false);
        yellow1.setEnabled(true);
        green1.setEnabled(true);
        playTeam1Label.setOpaque(true);
        playTeam2Label.setOpaque(true);
        playTeam1Label.setBackground(Color.blue);
        playTeam2Label.setBackground(Color.red);
        
        
    }//GEN-LAST:event_PLAYActionPerformed

    private void chooseplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseplayActionPerformed
        choosePanel.setVisible(false);
        playPanel.setVisible(true);
        
    }//GEN-LAST:event_chooseplayActionPerformed

    private void HISTORYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HISTORYActionPerformed
        playPanel.setVisible(false);
        choosePanel.setVisible(false);
        StartPanel.setVisible(false);
        historyPanel.setVisible(true);
    }//GEN-LAST:event_HISTORYActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void choosebackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosebackActionPerformed
        playPanel.setVisible(false);
        choosePanel.setVisible(false);
        StartPanel.setVisible(true);
        historyPanel.setVisible(false);
    }//GEN-LAST:event_choosebackActionPerformed

    private void blue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blue1ActionPerformed
        playTeam1Label.setBackground(Color.blue);
        chooseTeam1Label.setBackground(Color.blue);
        chooseTeam1Label.setOpaque(true);
        blue2.setEnabled(false);
        red2.setEnabled(true);
        yellow2.setEnabled(true);
        green2.setEnabled(true);
    }//GEN-LAST:event_blue1ActionPerformed

    private void red1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_red1ActionPerformed
        chooseTeam1Label.setBackground(Color.red);
        chooseTeam1Label.setOpaque(true);
        red2.setEnabled(false);
        blue2.setEnabled(true);
        yellow2.setEnabled(true);
        green2.setEnabled(true);
        playTeam1Label.setBackground(Color.red);
    }//GEN-LAST:event_red1ActionPerformed

    private void green1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_green1ActionPerformed
        chooseTeam1Label.setBackground(Color.green);
        chooseTeam1Label.setOpaque(true);
        blue2.setEnabled(true);
        red2.setEnabled(true);
        yellow2.setEnabled(true);
        green2.setEnabled(false);
        playTeam1Label.setBackground(Color.green);
    }//GEN-LAST:event_green1ActionPerformed

    private void yellow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellow1ActionPerformed
        chooseTeam1Label.setBackground(Color.yellow);
        chooseTeam1Label.setOpaque(true);
        blue2.setEnabled(true);
        red2.setEnabled(true);
        yellow2.setEnabled(false);
        green2.setEnabled(true);
        playTeam1Label.setBackground(Color.yellow);
    }//GEN-LAST:event_yellow1ActionPerformed

    private void blue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blue2ActionPerformed
        chooseTeam2Label.setBackground(Color.blue);
         chooseTeam2Label.setOpaque(true);
        blue1.setEnabled(false);
        red1.setEnabled(true);
        yellow1.setEnabled(true);
        green1.setEnabled(true);
        playTeam2Label.setBackground(Color.blue);
    }//GEN-LAST:event_blue2ActionPerformed

    private void red2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_red2ActionPerformed
        chooseTeam2Label.setBackground(Color.red);
         chooseTeam2Label.setOpaque(true);
        blue1.setEnabled(true);
        red1.setEnabled(false);
        yellow1.setEnabled(true);
        green1.setEnabled(true);
        playTeam2Label.setBackground(Color.red);
    }//GEN-LAST:event_red2ActionPerformed

    private void green2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_green2ActionPerformed
        chooseTeam2Label.setBackground(Color.green);
         chooseTeam2Label.setOpaque(true);
        blue1.setEnabled(true);
        red1.setEnabled(true);
        yellow1.setEnabled(true);
        green1.setEnabled(false);
        playTeam2Label.setBackground(Color.green);
    }//GEN-LAST:event_green2ActionPerformed

    private void yellow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellow2ActionPerformed
        chooseTeam2Label.setBackground(Color.yellow);
        chooseTeam2Label.setOpaque(true);
        blue1.setEnabled(true);
        red1.setEnabled(true);
        yellow1.setEnabled(false);
        green1.setEnabled(true);
        playTeam2Label.setBackground(Color.yellow);
    }//GEN-LAST:event_yellow2ActionPerformed

    private void commitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitActionPerformed
        
        
        score1=Integer.parseInt(TEAM1TXT.getText());
        scoreteam1=scoreteam1+score1;
        TEAM1SCORE.setText("");
        TEAM1SCORE.setText(TEAM1SCORE.getText()+scoreteam1);
        TEAM1TXT.setText("");
        
        
        score2=Integer.parseInt(TEAM2TXT.getText());
        scoreteam2=scoreteam2+score2;
         TEAM2SCORE.setText("");
        TEAM2SCORE.setText(TEAM2SCORE.getText()+scoreteam2);
        TEAM2TXT.setText("");
        
    }//GEN-LAST:event_commitActionPerformed

    private void TEAM1TITPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM1TITPLUSActionPerformed
        TEAM1SCORE.setText("");
        scoreteam1=scoreteam1+100;
        String text1=Integer.toString(scoreteam1);
        TEAM1SCORE.setText(TEAM1SCORE.getText()+scoreteam1);
    }//GEN-LAST:event_TEAM1TITPLUSActionPerformed

    private void TEAM2TITPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM2TITPLUSActionPerformed
        TEAM2SCORE.setText("");
        scoreteam2=scoreteam2+100;
        String text1=Integer.toString(scoreteam2);
        TEAM2SCORE.setText(TEAM2SCORE.getText()+scoreteam2);
    }//GEN-LAST:event_TEAM2TITPLUSActionPerformed

    private void TEAM1TITMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM1TITMINActionPerformed
        TEAM1SCORE.setText("");
        scoreteam1=scoreteam1-100;
        String text1=Integer.toString(scoreteam1);
        TEAM1SCORE.setText(TEAM1SCORE.getText()+scoreteam1);
    }//GEN-LAST:event_TEAM1TITMINActionPerformed

    private void TEAM2TITMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM2TITMINActionPerformed
        TEAM2SCORE.setText("");
        scoreteam2=scoreteam2-100;
        String text1=Integer.toString(scoreteam2);
        TEAM2SCORE.setText(TEAM2SCORE.getText()+scoreteam2);
    }//GEN-LAST:event_TEAM2TITMINActionPerformed

    private void TEAM1GRAPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM1GRAPLUSActionPerformed
        TEAM1SCORE.setText("");
        scoreteam1=scoreteam1+200;
        String text1=Integer.toString(scoreteam1);
        TEAM1SCORE.setText(TEAM1SCORE.getText()+scoreteam1);
    }//GEN-LAST:event_TEAM1GRAPLUSActionPerformed

    private void TEAM1GRAMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM1GRAMINActionPerformed
        TEAM1SCORE.setText("");
        scoreteam1=scoreteam1-200;
        String text1=Integer.toString(scoreteam1);
        TEAM1SCORE.setText(TEAM1SCORE.getText()+scoreteam1);
    }//GEN-LAST:event_TEAM1GRAMINActionPerformed

    private void TEAM2GRAPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM2GRAPLUSActionPerformed
        TEAM2SCORE.setText("");
        scoreteam2=scoreteam2+200;
        String text1=Integer.toString(scoreteam2);
        TEAM2SCORE.setText(TEAM2SCORE.getText()+scoreteam2);
    }//GEN-LAST:event_TEAM2GRAPLUSActionPerformed

    private void TEAM2GRAMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEAM2GRAMINActionPerformed
        TEAM2SCORE.setText("");
        scoreteam2=scoreteam2-200;
        String text1=Integer.toString(scoreteam2);
        TEAM2SCORE.setText(TEAM2SCORE.getText()+scoreteam2);
    }//GEN-LAST:event_TEAM2GRAMINActionPerformed

    private void endGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endGameActionPerformed
        StartPanel.setVisible(true);
        choosePanel.setVisible(false);
        playPanel.setVisible(false);
        historyPanel.setVisible(false);
        String txt1=Integer.toString(scoreteam1);
        String txt2=Integer.toString(scoreteam2);
        
        
        team1scoreHistory.setText(team1scoreHistory.getText()+"\n"+txt1);
        //team1scoreHistory.setText(team1scoreHistory.getText()+txt1);
        team2scoreHistory.setText(team2scoreHistory.getText()+"\n"+txt2);
        scoreteam1=0;
        scoreteam2=0;
        TEAM1SCORE.setText("0");
        TEAM2SCORE.setText("0");
    }//GEN-LAST:event_endGameActionPerformed

    private void backHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHistoryActionPerformed
        StartPanel.setVisible(true);
        choosePanel.setVisible(false);
        playPanel.setVisible(false);
        historyPanel.setVisible(false);
    }//GEN-LAST:event_backHistoryActionPerformed

    private void UNDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNDOActionPerformed
        TEAM1SCORE.setText("");
        scoreteam1=scoreteam1-score1;
        TEAM1SCORE.setText(TEAM1SCORE.getText()+scoreteam1);
        TEAM2SCORE.setText("");
        scoreteam2=scoreteam2-score2;
        TEAM2SCORE.setText(TEAM2SCORE.getText()+scoreteam2);     
    }//GEN-LAST:event_UNDOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    int scoreteam1,scoreteam2,score1,score2;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton HISTORY;
    private javax.swing.JButton PLAY;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JButton TEAM1GRAMIN;
    private javax.swing.JButton TEAM1GRAPLUS;
    private javax.swing.JLabel TEAM1SCORE;
    private javax.swing.JButton TEAM1TITMIN;
    private javax.swing.JButton TEAM1TITPLUS;
    private javax.swing.JTextField TEAM1TXT;
    private javax.swing.JButton TEAM2GRAMIN;
    private javax.swing.JButton TEAM2GRAPLUS;
    private javax.swing.JLabel TEAM2SCORE;
    private javax.swing.JButton TEAM2TITMIN;
    private javax.swing.JButton TEAM2TITPLUS;
    private javax.swing.JTextField TEAM2TXT;
    private javax.swing.JButton UNDO;
    private javax.swing.JButton backHistory;
    private javax.swing.JButton blue1;
    private javax.swing.JButton blue2;
    private javax.swing.JPanel choosePanel;
    private javax.swing.JLabel chooseTeam1Label;
    private javax.swing.JLabel chooseTeam2Label;
    private javax.swing.JButton chooseback;
    private javax.swing.JButton chooseplay;
    private javax.swing.JButton commit;
    private javax.swing.JButton endGame;
    private javax.swing.JButton green1;
    private javax.swing.JButton green2;
    private javax.swing.JLabel historyLabel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel playPanel;
    private javax.swing.JLabel playTeam1Label;
    private javax.swing.JLabel playTeam2Label;
    private javax.swing.JButton red1;
    private javax.swing.JButton red2;
    private javax.swing.JTextPane team1scoreHistory;
    private javax.swing.JTextPane team2scoreHistory;
    private javax.swing.JButton yellow1;
    private javax.swing.JButton yellow2;
    // End of variables declaration//GEN-END:variables
}
